#!/usr/bin/env python3
"""Explicit scene specifications for question art without an explainer diagram."""

from __future__ import annotations


# Questions with explainer diagrams obtain their scene nodes from
# generate_explainer_art. Every remaining question is listed here explicitly.
# There is deliberately no keyword or chapter-level fallback: adding or
# renumbering a page must also update
# its illustration specification.
MANUAL_SCENES: dict[int, tuple[str, tuple[str, ...]]] = {
    # Topic 01: light, sky, time, and cold.
    3: ("compare", ("cloud", "light", "shadow")),
    4: ("flow", ("sun", "cloud", "light")),
    6: ("compare", ("object-light", "shadow", "sun-ground")),
    8: ("flow", ("window-light", "light", "eye")),
    14: ("compare", ("star-field", "sun", "eye")),
    15: ("orbit", ("sun", "half-earth", "rotation")),
    16: ("orbit", ("earth", "rotation", "sun-ground")),
    18: ("network", ("tilted-earth", "sun", "cool-air")),
    19: ("layers", ("frost-leaf", "ice", "crystal-spacing")),
    22: ("flow", ("breath", "cool-air", "cloud")),
    24: ("layers", ("coat", "air-layers", "heat-out")),
    25: ("network", ("hat", "body", "heat-out")),
    27: ("cycle", ("calendar", "rotation", "clock", "counter")),
    28: ("cycle", ("week", "sun", "moon", "counter")),
    29: ("network", ("sleep", "brain", "moon")),
    30: ("network", ("owl", "moon", "sound-wave", "eye")),

    # Topic 02: air, weather, and water.
    34: ("compare", ("wind", "warm-air", "cool-air")),
    43: ("flow", ("lightning", "air", "sound-wave")),
    45: ("layers", ("cloud", "tiny-drops", "air")),
    46: ("flow", ("leaf", "cool-air", "beading-drop")),
    48: ("flow", ("wet-paper", "wind", "vapor")),
    49: ("compare", ("vapor", "cloud", "water-particles")),
    51: ("flow", ("vapor", "cold-water", "beading-drop")),
    53: ("forces", ("water", "incline", "gravity-center")),
    54: ("layers", ("water", "sediment-layers", "igneous-rock")),
    55: ("flow", ("water", "pressure", "home")),
    57: ("layers", ("water", "beading-drop", "oily-feather")),
    58: ("compare", ("cloud", "earth-air")),
    59: ("network", ("satellite", "cloud", "receiver", "air")),

    # Topic 03: plants and gardens.
    64: ("layers", ("stem", "xylem", "vein")),
    69: ("network", ("flower", "light", "wave")),
    70: ("layers", ("flower", "spores", "molecule")),
    72: ("layers", ("fruit", "seed", "embryo")),
    75: ("forces", ("seed", "water", "force-up", "force-down")),
    77: ("layers", ("tree", "xylem", "skin")),
    78: ("flow", ("tree", "cool-air", "leaf")),
    79: ("compare", ("tree", "leaf", "snow")),
    80: ("network", ("leaf", "water", "hot-drop")),
    82: ("flow", ("stem", "tree", "light")),
    85: ("layers", ("water", "leaf", "shadow")),
    86: ("cycle", ("spores", "sprout", "leaf", "spores")),
    87: ("compare", ("stem", "tree")),
    88: ("compare", ("stem", "root", "seed-food")),
    89: ("layers", ("root", "seed-food", "leaf")),
    90: ("network", ("flower", "bee", "long-worm", "bird")),

    # Topic 04: small animals and habitats.
    94: ("network", ("ant-food", "ant-line", "body")),
    96: ("flow", ("butterfly", "flower", "straw")),
    98: ("layers", ("insect", "skin", "insect-body")),
    99: ("compare", ("insect", "varied-insects")),
    101: ("flow", ("insect", "skin", "blood-oxygen")),
    104: ("flow", ("insect", "bird-wing", "sound-wave")),
    105: ("forces", ("insect", "lever", "force-up")),
    107: ("layers", ("snail", "skin", "body")),
    110: ("network", ("long-worm", "root", "air")),
    111: ("compare", ("long-worm", "short-worm")),
    112: ("flow", ("insect", "coiled-chain", "body")),
    114: ("compare", ("spider", "web", "slip")),
    115: ("layers", ("landscape", "igneous-rock", "varied-insects")),
    116: ("cycle", ("egg", "fish", "body", "water")),
    117: ("forces", ("body", "spring", "motion-arrow")),

    # Topic 05: animal adaptations.
    127: ("network", ("bird", "molecule", "fruit")),
    128: ("network", ("body", "hair", "lung", "gas-exchange")),
    129: ("flow", ("fish", "lung", "air")),
    131: ("network", ("bird-wing", "sound-wave", "ear")),
    134: ("layers", ("camouflage", "light", "eye")),
    136: ("layers", ("hair", "light", "eye")),
    137: ("network", ("body", "leaf", "intestine")),
    138: ("layers", ("body", "embryo", "skin")),
    139: ("network", ("body", "leaf", "energy")),
    140: ("layers", ("hair", "skin", "body")),
    143: ("network", ("body", "wave", "brain")),
    144: ("cycle", ("leaf", "teeth", "stomach", "intestine")),
    148: ("compare", ("fish", "compact-bone", "spongy-marrow")),
    149: ("network", ("squid", "muscle", "body")),
    150: ("network", ("body", "step-one", "landscape")),
    151: ("flow", ("bird", "globe", "body")),

    # Topic 06: body, senses, and health.
    162: ("flow", ("exhale", "lung", "sound-wave")),
    163: ("layers", ("brain", "cell", "molecule")),
    166: ("compare", ("eye", "eye-lens", "light")),
    167: ("layers", ("eye", "water", "drop")),
    170: ("flow", ("wave", "air", "brain")),
    171: ("network", ("molecule", "teeth", "brain")),
    172: ("network", ("molecule", "eye", "brain")),
    173: ("compare", ("teeth", "wedge")),
    174: ("flow", ("teeth", "bone", "cell")),
    176: ("flow", ("stomach", "molecule", "sound-wave")),
    177: ("network", ("vessel", "water", "molecule")),
    178: ("layers", ("skin", "water", "heat")),
    179: ("layers", ("skin", "hair", "cool-air")),
    180: ("flow", ("hand", "micelle", "clean-water")),
    181: ("layers", ("skin", "blood-oxygen", "cell")),

    # Topic 07: tools, machines, and building.
    182: ("network", ("lever", "wheel-cart", "gear-contact")),
    188: ("cycle", ("bicycle", "small-gear", "gear-contact", "large-gear")),
    193: ("compare", ("spring", "coiled-chain", "stretched-chain")),
    195: ("network", ("magnet", "earth-field", "field")),
    198: ("layers", ("battery", "charge", "molecule")),
    201: ("flow", ("motor", "rotor", "wind")),
    202: ("flow", ("motor", "pressure", "water")),
    204: ("network", ("lever", "wedge", "hand")),
    205: ("flow", ("hooklets", "gear-contact", "closed-circuit")),
    206: ("compare", ("lock-key", "gear-contact")),
    207: ("forces", ("lever", "rotation", "anchor")),
    208: ("layers", ("truss", "weight", "force-up")),
    209: ("forces", ("arch", "force-up", "force-down")),
    210: ("network", ("pulley", "rope-segments", "weight")),
    211: ("flow", ("lift", "counter", "receiver")),
    212: ("network", ("receiver", "eye", "motor", "brain")),

    # Topic 08: Earth, maps, and climate.
    214: ("compare", ("globe", "landscape")),
    223: ("layers", ("weathering", "sediment-layers", "root")),
    224: ("layers", ("igneous-rock", "bone", "sediment-layers")),
    225: ("network", ("globe", "landscape", "map")),
    228: ("network", ("earth-field", "sun", "receiver")),
    230: ("layers", ("globe", "latitude", "map")),
    231: ("flow", ("sun", "half-earth", "heat")),
    233: ("orbit", ("half-earth", "sun", "body")),
    234: ("compare", ("landscape", "water")),
    235: ("compare", ("landscape", "water", "map")),
    236: ("compare", ("water", "landscape", "map")),
    238: ("layers", ("landscape", "hot-drop", "water")),
    239: ("layers", ("tree", "leaf", "bird")),
    240: ("network", ("leaf", "wind", "body")),
    242: ("layers", ("mountain", "water", "crystal-spacing")),
    243: ("compare", ("map", "landscape", "border")),

    # Topic 09: oceans and coasts.
    248: ("layers", ("ocean-light", "water", "deep-object")),
    253: ("network", ("water", "varied-insects", "current")),
    254: ("network", ("leaf", "sun", "air")),
    256: ("compare", ("star", "fish")),
    257: ("network", ("body", "water", "matter")),
    259: ("layers", ("snail", "shell", "crab-side")),
    264: ("network", ("fish", "coral", "clean-water")),
    266: ("layers", ("tree", "water", "salt")),
    267: ("compare", ("broad-leaf", "water", "root")),
    268: ("compare", ("leaf", "water", "spores")),
    269: ("layers", ("shell", "body", "water")),
    270: ("layers", ("weathering", "sediment-layers", "water")),
    271: ("flow", ("wind-wave", "sediment-layers", "current")),
    272: ("flow", ("plastic-bottle", "current", "matter")),
    273: ("network", ("fish", "firefly-light", "ocean-light")),

    # Topic 10: space and exploration.
    274: ("network", ("galaxy", "star", "planet", "matter")),
    276: ("compare", ("sun", "earth")),
    278: ("network", ("planet", "orbit", "star")),
    279: ("orbit", ("sun", "planet", "saturn", "earth")),
    283: ("layers", ("planet", "iron", "hot-drop")),
    284: ("layers", ("planet", "vortex", "wind")),
    286: ("orbit", ("planet", "rotation", "tilted-earth")),
    287: ("network", ("planet", "wind", "cool-air")),
    288: ("compare", ("planet", "moon", "orbit")),
    289: ("network", ("asteroids", "planet", "impact")),
    293: ("forces", ("moon", "body", "force-up", "force-down")),
    298: ("network", ("matter", "star", "air")),
    300: ("layers", ("rocket", "body", "air")),
    301: ("network", ("satellite", "earth", "receiver")),
    302: ("flow", ("star", "eye-lens", "eye")),
    303: ("network", ("star", "orbit", "galaxy")),

    # Topic 11: materials, food, and the home.
    306: ("network", ("matter", "atom", "molecule")),
    311: ("flow", ("molecule", "water", "teeth")),
    313: ("flow", ("light", "liquid-particles", "eye")),
    315: ("layers", ("coiled-chain", "stretched-chain", "protein-network")),
    317: ("flow", ("fruit", "air", "enzyme")),
    320: ("flow", ("vapor", "cold-particles", "ice-lattice")),
    322: ("flow", ("heat", "metal", "bread")),
    324: ("forces", ("wood", "force-up", "force-down")),
    326: ("compare", ("paper-fibers", "crack")),
    328: ("flow", ("iron", "water", "air")),
    329: ("network", ("matter", "coiled-chain", "molecule")),
    331: ("flow", ("matter", "heat", "igneous-rock")),
    332: ("layers", ("rope-segments", "web", "paper-fibers")),
    333: ("cycle", ("wheel-cart", "water", "rotation", "matter")),
    334: ("flow", ("air", "pressure", "matter")),

    # Topic 12: transport, energy, environment, and scientific practice.
    338: ("forces", ("train-wheel", "motion-arrow", "force-down")),
    340: ("network", ("circuit", "clock", "traffic-light")),
    342: ("flow", ("power-plant", "circuit", "train-wheel")),
    349: ("network", ("sun", "wind", "water", "energy")),
    352: ("flow", ("water", "rotor", "generator")),
    354: ("flow", ("circuit", "light", "heat")),
    355: ("layers", ("home", "air-layers", "heat-out")),
    356: ("cycle", ("matter", "energy", "molecule", "matter")),
    357: ("cycle", ("leaf", "mycelium", "matter", "leaf")),
    358: ("flow", ("air", "tree", "matter")),
    360: ("network", ("tree", "bird", "varied-insects", "fish")),
    361: ("compare", ("eye", "brain", "question")),
    362: ("flow", ("measure", "counter", "map")),
    363: ("compare", ("experiment", "receiver", "counter")),
    364: ("network", ("model", "eye", "map")),
    365: ("network", ("question", "brain", "star", "seed")),
}


CUSTOM_ICON_KEYS = {
    "arch",
    "asteroids",
    "border",
    "breath",
    "calendar",
    "coat",
    "experiment",
    "frost-leaf",
    "galaxy",
    "hat",
    "latitude",
    "lock-key",
    "measure",
    "model",
    "owl",
    "plastic-bottle",
    "question",
    "shell",
    "sleep",
    "star-field",
    "traffic-light",
    "truss",
    "week",
    "wood",
}


# The first node in these pages is a concrete, child-recognizable subject.  The
# remaining nodes still show the mechanism, structure, or environmental clue.
# Prefix renderers in generate_question_art keep species distinct without changing
# the rigorously selected explainer diagrams embedded later in each article.
SUBJECT_ICONS: dict[int, str] = {
    # Topic 04: one silhouette must not stand in for every small animal.
    91: "insect-general",
    92: "insect-spider",
    93: "insect-ant",
    94: "insect-ant-nest",
    95: "insect-bee",
    96: "insect-butterfly",
    97: "insect-caterpillar",
    98: "insect-beetle",
    99: "insect-ladybug",
    100: "insect-firefly",
    101: "insect-mosquito",
    102: "insect-dragonfly",
    103: "insect-grasshopper",
    104: "insect-cricket",
    105: "insect-mantis",
    106: "insect-stick",
    107: "small-snail",
    108: "small-snail-trail",
    109: "small-earthworm",
    110: "small-earthworm-soil",
    111: "small-centipede",
    112: "small-pillbug",
    113: "insect-spiderweb",
    114: "insect-spider",
    115: "small-rock-habitat",
    116: "small-frog-cycle",
    117: "small-frog",
    118: "small-gecko",
    119: "small-lizard",
    120: "small-chameleon",

    # May: exact animal silhouettes replace generic feathers and stick figures.
    121: "bird-feather",
    122: "bird-flight",
    123: "bird-penguin",
    124: "bird-duck",
    125: "bird-woodpecker",
    126: "bird-owl",
    127: "bird-flamingo",
    128: "mammal-group",
    129: "aquatic-whale",
    130: "aquatic-dolphin",
    131: "mammal-bat",
    132: "mammal-elephant",
    133: "mammal-giraffe",
    134: "mammal-zebra",
    135: "mammal-camel",
    136: "mammal-polar-bear",
    137: "mammal-panda",
    138: "mammal-kangaroo",
    139: "mammal-sloth",
    140: "mammal-hedgehog",
    141: "mammal-rabbit",
    142: "mammal-cat",
    143: "mammal-dog",
    144: "mammal-cow",
    145: "mammal-horse",
    146: "aquatic-fish",
    147: "aquatic-fish-bladder",
    148: "aquatic-shark",
    149: "aquatic-octopus",
    150: "mammal-footprints",
    151: "bird-migration",

    # August: geographic forms must differ before their definitions are read.
    217: "geo-continents",
    218: "geo-earthquake",
    219: "geo-volcano",
    220: "geo-mountain",
    221: "geo-valley",
    222: "geo-rock-mineral",
    223: "geo-soil",
    224: "geo-fossil",
    225: "geo-continents",
    226: "geo-map",
    227: "geo-projection",
    228: "geo-compass",
    229: "geo-gps",
    230: "geo-latitude",
    231: "geo-equator",
    232: "geo-poles",
    233: "geo-timezones",
    234: "geo-island",
    235: "geo-peninsula",
    236: "geo-lake-sea",
    237: "geo-delta",
    238: "geo-desert",
    239: "geo-rainforest",
    240: "geo-grassland",
    241: "geo-glacier",
    242: "geo-cave",
    243: "geo-border",

    # September: exact organisms and coastal forms replace generic fish/water.
    253: "ocean-plankton",
    254: "ocean-algae",
    255: "ocean-jellyfish",
    256: "ocean-starfish",
    257: "ocean-sea-cucumber",
    258: "ocean-crab",
    259: "ocean-hermit-crab",
    260: "ocean-octopus",
    261: "ocean-squid",
    262: "ocean-whale-shark",
    263: "ocean-seahorse",
    264: "ocean-clownfish",
    265: "ocean-turtle",
    266: "ocean-mangrove",
    267: "ocean-seagrass",
    268: "ocean-seaweed",
    269: "ocean-shell",
    270: "ocean-sand",
    271: "ocean-shore-drift",
    272: "ocean-plastic",
    273: "ocean-bioluminescent-fish",

    # October: planets and space tools receive recognizable silhouettes.
    274: "space-universe",
    275: "space-star",
    276: "space-scale",
    277: "space-solar-system",
    278: "space-planet",
    279: "space-planets",
    280: "space-mercury",
    281: "space-venus",
    282: "space-earth-water",
    283: "space-mars",
    284: "space-jupiter",
    285: "space-saturn",
    286: "space-uranus",
    287: "space-neptune",
    288: "space-pluto",
    289: "space-asteroids",
    290: "space-comet",
    291: "space-meteor",
    292: "space-crater",
    293: "space-moon-gravity",
    294: "space-solar-eclipse",
    295: "space-lunar-eclipse",
    296: "space-orbit",
    297: "space-rocket",
    298: "space-vacuum",
    299: "space-astronaut",
    300: "space-suit",
    301: "space-satellite",
    302: "space-telescope",
    303: "space-galaxy",
    304: "space-black-hole",
}
